### ISSUE TITLE
Sync issue: Item based tags are not synced

### ISSUE THREAD

**Issue by sualfred** [Montellese/mediaimporter.emby#19]
Like Kodi Emby offers the option to add tags to items. 
These tags are not synced. The information is stored in the "TagItems" JSON key and should be applied for the item type TV shows and movies.

Example:
Library 'HDR Serien' -> "Our Planet" on Emby tagged with "Documentary"

Kodi with mediaimporter:
"Our Planet" -> Tags: "HDR Serien"

Kodi with Emby for Kodi (how it should be):
"Our Planet" -> Tags: "HDR Serien", "Documentary"

**Comment by Montellese** [comment]
Thanks for the report. Do you know what the difference between the `Tags` and the `TagItems` property is? Right now I'm only retrieving and syncing the `Tags` property but since I don't have any tags set in my Emby library I never really noticed that something might not be working.

**Comment by sualfred** [comment]
I don't know what `Tags` is used for but it is empty for my items with custom tags while `TagItems` has them stored.

**Comment by Montellese** [comment]
Fixed in master. Odd thing is you have to specify that you want to get the `Tags` field to get both the `TagItems` and `Tags` field. Specifying the `TagItems` field doesn't work.

**Comment by sualfred** [comment]
@Montellese 

Just tested it and tags still won't be synced.
